FROM node:current-alpine

RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Europe/Paris /etc/localtime

# (API)
# EXPOSE 3000
# (Websocket)
EXPOSE 3001

WORKDIR	/var/nestjs

ENTRYPOINT	npm i && npm run build && npm run start