version: '3.1'

services:
  # Sapper:
  #   depends_on:
  #     - NestJS
  #   container_name: Sapper
  #   build: ./sapper
  #   image: sapper
  #   hostname: sapper
  #   env_file:
  #     - .env
  #   ports:
  #     - 80:80 
  #   volumes:
  #     - ./sapper:/var/sapper
  #   networks:
  #     - transcendence-network
  #   restart: always

  NestJS:
    depends_on:
      - PostGresSQL
    container_name: NestJS
    build: ./nestjs
    image: nestjs
    hostname: nestjs
    env_file:
      - .env
    ports:
      - 3000:3000 # remove for prod
    volumes:
      - ./nestjs:/var/nestjs
    networks:
      - transcendence-network
    restart: always

  PostGresSQL:
    container_name: PostGresSQL
    image: postgres
    hostname: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: fttrans
    ports:
      - 5432:5432 # remove for prod
    volumes:
      - ./PostGresSQL-data:/var/lib/postgresql/data
    networks:
      - transcendence-network
    restart: always

networks:
    transcendence-network:
        name: transcendence-network
        driver: bridge

volumes:
    PostGresSQL-data:
        name: PostGresSQL-data
        driver: local
        driver_opts:
            type: none  
            o: bind
            device: ./PostGresSQL-data
